name: Demo CI/CD

on:
  push:
    branches:
      - main

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: log using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/mirai/demo-oprec
            echo "halo! cicd berhasil" >> log.txt
